version: 1.0.{build}
image: Ubuntu1604
environment:
  github_access_token:
    secure: XaPhHBNztDcP1eTiOWEKAd8wYcW9bvK5e8NFZJDgCFBf0f48tMI1r5hT19jSc2sQ
install:
- sh: >-
    rvm use 2.5.3

    gem install gepub
    
#    docker pull raabf/texstudio-versions:texlive2018
build_script:
- sh: >-
    ruby epub/make_epub.rb
    
    
for:
- 
  branches:
    only:
      - master
  deploy_script:
  - git config --global user.email "recollectionforgot@gmail.com"
  - git config --global user.name "Finnite"
  - git remote rm origin
  - git remote add origin https://hxdnshx:$github_access_token@github.com/hxdnshx/n8440fe.git
  - git fetch --all
  - git checkout gh-pages origin/gh-pages
  - git reset @~
  - git rebase master
  - ruby epub/make_epub.rb
#  - docker run --rm -v $(pwd):/workdir --it raabf/texstudio-versions:texlive2018 bash -c /workdir/build_pdf.sh
  - git add .
  - git commit -m "update"
  - git push -f
