version: 1.0.{build}
image: Ubuntu1604
install:
- sh: >-
    set PATH=C:\Ruby22\bin;%PATH%

    gem install gepub

    sudo apt-get update && sudo apt-get install -y --quiet --no-install-recommends latexmk
build_script:
- sh: >-
    ruby epub\make_epub.rb

    latexmk -cd -f -lualatex -interaction=nonstopmode -synctex=1 n8440fe.tex
artifacts:
- path: '*.epub'
- path: '*.pdf'
