version: 1.0.{build}
image: Ubuntu1604
environment:
  github_access_token:
    secure: XaPhHBNztDcP1eTiOWEKAd8wYcW9bvK5e8NFZJDgCFBf0f48tMI1r5hT19jSc2sQ
install:
- sh: >-
    bundle install

    rvm use 2.5.3

    bundle install

    ruby gem install gepub
build_script:
- sh: >-
    ruby epub\make_epub.rb
for:
- 
  branches:
    only:
      - master
  deploy_script:
  - git config --global credential.helper store
